version: "3"

tasks:
  run:
    env:
      config: docker
    cmds:
      - go run ./cmd/auth/main.go

  proto:
    cmds:
      - protoc --go_out=./proto --go-grpc_out=./proto --proto_path=./proto ./proto/*.proto

  tidy:
    cmds:
      - go mod tidy

  test:
    cmds:
      - go test ./...

  docker:
    cmds:
      - echo "Starting docker containers"
      - docker run -d --name jaeger -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 14250:14250 -p 9411:9411 jaegertracing/all-in-one:1.72.0
      - docker-compose -f docker-compose.yml up --build
