FROM golang:1.25.4

ENV TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

ENV config=docker

WORKDIR /app

COPY ./ /app

RUN go mod download

RUN go install github.com/githubnemo/CompileDaemon@latest

EXPOSE 5001

ENTRYPOINT CompileDaemon --build="go build cmd/auth/main.go" --command="./main"
